services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
  api:
    depends_on:
      - db
    build: ./api
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://db:27017/app_development
  webapp:
    depends_on:
      - api
    build: ./webapp
    volumes:
      - static_volume:/opt/app/static
    ports:
      - 8010:8010
    environment:
      - DJANGO_DEBUG=True
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - db
      - webapp
      - api
volumes:
  static_volume:
