services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
  api:
    depends_on:
      - db
    build: ./api
    ports:
      - 3001:3001
    environment:
      - MONGO_URL=mongodb://db:27017/app_development
  webapp:
    depends_on:
      - api
    build: ./webapp
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    ports:
      - 8000:8000
    depends_on:
      - db
      - webapp
      - api
