services:
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db
  api:
    depends_on:
      - db
    build: .
    ports:
      - 3100:80
    environment:
      - MONGO_URL=mongodb://db:27017/app_development
  webapp:
    depends_on:
      - api
    build: ../webapp
    ports:
      - 8010:8010
    environment:
      - DJANGO_DEBUG=True
  nginx:
    depends_on:
      - api
    build: ..
    ports:
      - 8888:8888
      - 8889:8889
    extra_hosts:
      - "host.docker.internal:host-gateway"
